### ISSUE TITLE
Установка FTP модуля без требования dev зависимостей

### ISSUE THREAD

**Issue by r4sas** [gameap/gameap.github.io#1]
Текущая команда для composer начинает вытягивать за собой всю dev начинку.
Чтобы этого не происходило, можно поменять команду на следующую:
```bash
composer require --update-no-dev fzaninotto/faker "^1.8" gameap/ftp-module "^1.1"
```
Почему fzaninotto/faker не тяется при no-dev, я не знаю. Возможно у вас он не прописан в зависмостях ftp-module.

**Comment by r4sas** [comment]
@et-nik bump?

**Comment by et-nik** [comment]
@r4sas было исправлено, спасибо
